# Generated by Django 4.1 on 2022-08-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Companies",
            new_name="Company",
        ),
    ]
